version: '3'

  cli:
    container_name: cli
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    command: bash -c "tail -f /dev/null"
    volumes:
      - ./cli:/var/www/.
    network_mode: host