name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run Tests
        run: |
          docker-compose up -d
          sleep 5
          docker exec app deno test -A

  linter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Formatter
        run: deno fmt --check

      - name: linter
        run: deno lint