name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  app-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Run Tests
        run: |
          docker-compose up -d app
          sleep 10
          cd app
          deno test -A --unstable

  cli-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensure cli works
        run: |
          docker-compose up -d cli
          mkdir 'D:/Music/Song with Increase Vol' 
          sh cli/convert.sh

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Formatter
        run: deno fmt --check
      - name: linter
        run: deno lint